doc ///
    Key
        cayleyMengerIdeal
        (cayleyMengerIdeal, ZZ, ZZ)
    Headline
        constructs the ideal generated by the Cayley-Menger relations for a set of points in real Euclidean space
    Usage
        cayleyMengerIdeal(n,d)
    Inputs
        n : ZZ
            the number of points
        d : ZZ
            the dimension of the real Euclidean space
    Outputs
        : Ideal
            the ideal generated by the Cayley-Menger relations
    Description
        Text
            Given $n$ points in $d$-dimensional real Euclidean space, this function constructs
	    the ideal generated by the Cayley-Menger relations of their pairwise squared distances.

	    The relations are the $d+3$ by $d+3$ minors of the $n+1$ by $n+1$ Cayley-Menger matrix.
	    This is the defining ideal of the Cayley-Menger variety for $n$ points in $d$-dimensional Euclidean
	    space.

	    A set of $n$ points in Euclidean space lie in a $d$-dimensional affine subspace if and only if
	    their pairwise squared distances satisfy these relations.
        Example
            cayleyMengerIdeal(5,2)
///